server:
  port: 8087

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_audit
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    com.jeimandei: INFO
    org.springframework: WARN
    org.hibernate: WARN
