server:
  port: 8083

spring:
  application:
    name: church-cms-service
  datasource:
    url: jdbc:postgresql://localhost:5432/church_db
    username: church_app
    password: church_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 3JkWpV9nR7mQfLxTzYsA2bDcEhGiJuKoNvPwSyUaBdFeHjIlMnOqRtVxZy1235467890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  expiration: 86400000

logging:
  level:
    com.jeimandei: DEBUG
